### ISSUE TITLE
provide more error message description (if possible)

### ISSUE THREAD

**Issue by pjenviri** [axelarnetwork/axelarjs-sdk#110]
I tested the manual approval button on Axelarascan (with the SDK version `0.6.11-alpha.3`) and got `unknown error` response. Would it be possible to parse more detail of the error?

the transaction: https://testnet.axelarscan.io/gmp/0xa3f8f2590faa2221dc51f9993bde23b85995d39fd4fd50d0d261d659dc8c45e5

<img width="1440" alt="Screen Shot 2565-07-07 at 00 25 05" src="https://user-images.githubusercontent.com/87146398/177609898-63bcfe46-e8c4-4344-abe9-f277a455b940.png">

**Comment by canhtrinh** [comment]
@pjenviri i believe a lot of this may have been addressed in 0.6.12 that we published last week. can you try to run the same failures with the new version and let me know if you continue to see issues? 

it looks like the tx pasted in this issue resolved somehow, so if we can identify other txs where you've seen similar issues, that'll help us debug further. 

thanks! cc @npty

**Comment by pjenviri** [comment]
@canhtrinh Thanks for the update.

I tested the Approve button [SDK ver.`0.6.13`] on 3 calls, and they all returned `cannot sign command`. after a while (~5 mins), two of them were approved.
- https://testnet.axelarscan.io/gmp/0xbf3321ab5e1294cd3b53f9052703170ced4256e26c5ce53150ade81da5d6f1f2
- https://testnet.axelarscan.io/gmp/0x256a2d77d91d57afccfb0263d53a70c5752c8e556f15e8490e66bfe65af50ad2

but this one is still not:
- https://testnet.axelarscan.io/gmp/0x5d5c0c5585cfc425c30e2899be64ef9e47e29fc157b0365c13a7619407e87e6e

you can also randomly try it more at https://testnet.axelarscan.io/gmp/search?status=called. the page lists all calls that are waiting for approval. hope it helps. cc. @npty 

<img width="1440" alt="Screen Shot 2565-07-19 at 10 39 45" src="https://user-images.githubusercontent.com/87146398/179690991-527f3598-e13d-4c97-850c-892ac82a65d3.png">
<img width="1440" alt="Screen Shot 2565-07-19 at 10 39 27" src="https://user-images.githubusercontent.com/87146398/179691005-556bdf12-78d9-4e1d-8bdd-d61d9b650052.png">
<img width="1440" alt="Screen Shot 2565-07-19 at 10 45 47" src="https://user-images.githubusercontent.com/87146398/179690971-8c82a498-30bc-44ba-b048-1d25f54bb5a3.png">

**Comment by pjenviri** [comment]
update:
I tested some more transactions. 

returned `cannot sign command` but got approved:
- https://testnet.axelarscan.io/gmp/0x8797c31874174e7fc68b9a2772ba2d8462c0bc5e477543bfd1331ee522fa4bfc
- https://testnet.axelarscan.io/gmp/0xce6d9c14c3846b0e8deaf7f9c92d6c2eb9b25d569a2231c115474761fe11969d

not approved calls:
`Bad status on response: 429`
- https://testnet.axelarscan.io/gmp/0xb8057d529746d929fe01ce7cec58f7db1c39871cf6ee951b65bf2b27972b4f8c
- https://testnet.axelarscan.io/gmp/0x12c75572c90a1b9ff02f118cdb11542e27ec91d16a547ff1f4d7688c90f0992a
- https://testnet.axelarscan.io/gmp/0xa41b6a75a36f06d1a2164e20b781a67955387f21ecbffba157c9bc2607d6eda9
<img width="1440" alt="Screen Shot 2565-07-19 at 15 04 09" src="https://user-images.githubusercontent.com/87146398/179699741-b190f625-8384-4fef-9536-dd2e425fc78e.png">

`account sequence mismatch`:
- https://testnet.axelarscan.io/gmp/0x4e481d0c9e4ec7ff56f4c17c178d1253754ac7cd693867183d0fe77c3fce2c2b
<img width="1440" alt="Screen Shot 2565-07-19 at 15 05 02" src="https://user-images.githubusercontent.com/87146398/179699714-4874a60f-f787-4f1e-86ad-9f9cddb78d99.png">

`cannot sign command`:
https://testnet.axelarscan.io/gmp/0x148031bce691b0025928b5e5f911a82fd27f224d7d14cd3f428381553d2bb2c1
<img width="1440" alt="Screen Shot 2565-07-19 at 15 09 32" src="https://user-images.githubusercontent.com/87146398/179700634-5f0d0296-42a1-46b0-89e6-4684fe1b9cd1.png">

**Comment by npty** [comment]
fixed: https://github.com/axelarnetwork/axelarjs-sdk/pull/106
