### ISSUE TITLE
Add an api to check key rotation issue 

### ISSUE THREAD

**Issue by npty** [axelarnetwork/axelarjs-sdk#112]
From @milapsheth 

```
axelard q tss next-key-id [chain] secondary if this returns a key I'd (and doesn't panic), then a key rotation is in progress
```

**Comment by canhtrinh** [comment]
don't htink we'll need this. 
there's also a built-in query that can be used anyway: 
`      const api: AxelarQueryClientType = await AxelarQueryClient.initOrGetAxelarQueryClient(config);
      const params: NextKeyIDRequest = { chain: "avalanche", keyRole: 1 };
      const result: NextKeyIDResponse = await api.tss.NextKeyID(params);`
