### ISSUE TITLE
add method to query network status

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelarjs-sdk#163]
wrapper for https://axelar-lcd.quickapi.com/axelar/nexus/v1beta1/chains?status=1

then build into `estimateGasFee` and return error if either src or dest chains is not in active set.

**Comment by canhtrinh** [comment]
e.g. `this.axelarQueryClient.nexus.Chains({ status: 1});` @npty

**Comment by npty** [comment]
#210
