### ISSUE TITLE
require all methods to take chainId (not chain name) as parameters

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelarjs-sdk#197]
before, we allowed devs to input chain name instead of chain ID (as recognized by the Axelar network) for ease of use. 

however, now that we have GMP that require chainID instead, we should update all SDK methods to require chain Ids instead. 
example: in testnet, ethereum (goerli) is recognized on the Axelar network as `ethereum-2`, while `ethereum` refers to ropsten.

cc @milapsheth and @vladwulf for viz.

**Comment by npty** [comment]
Fixed by #202 and #206
