### ISSUE TITLE
The sdk returns "cannot find chainethereum-2" for `manualRelayToDestChain`

### ISSUE THREAD

**Issue by pjenviri** [axelarnetwork/axelarjs-sdk#200]
https://testnet.axelarscan.io/gmp/0x5408060a6e15e4f5fa04ea3bec0da8a01ce5585c48321c151264184f489bbd9e:32
the Approve button calls  `manualRelayToDestChain(transactionHash)` under the hood.

<img width="1440" alt="inage1" src="https://user-images.githubusercontent.com/87146398/201057891-333a9ea1-309d-45bb-a289-d7e4485dc083.png">

**Comment by npty** [comment]
#206
