### ISSUE TITLE
Add chain id suggestion for AxelarQueryAPI methods

### ISSUE THREAD

**Issue by vladwulf** [axelarnetwork/axelarjs-sdk#208]
When running this
```ts
const fee = await query.getTransferFee("osmosis", "avalanche", "uausdc", 1000000);
// instead of 
const fee = await query.getTransferFee("osmosis-4", "avalanche", "uausdc", 1000000);
```
We get 
`Error: Query failed with (18): uausdc is not a registered asset on chain osmosis: nexus error: invalid request`

We should provide the same chain id suggestion as what we have with `getDepositAddress`

**Comment by npty** [comment]
#211
