### ISSUE TITLE
GMP Transaction Recovery: `network chainId mismatch` error when manually executing on Arbitrum testnet.

### ISSUE THREAD

**Issue by pjenviri** [axelarnetwork/axelarjs-sdk#246]
Step to reproduce:
1.  please go to https://testnet.axelarscan.io/gmp/0x9649a3aa3ef3951f72c23ece6f4ebc36242644388e077271e57e71d991d472c2:48
2. click the Execute button. 
3. the error message pops up.
<img width="1440" alt="Screenshot 2566-02-14 at 03 21 36" src="https://user-images.githubusercontent.com/87146398/218566449-6361f95a-9827-4dbe-9a6e-5e100f5256b4.png">

I tested the button on other chains (ie. avalanche fuji, fantom, moonbase testnet), they worked fine except Arbitrum.

**Comment by canhtrinh** [comment]
this was fixed in this commit: https://github.com/axelarnetwork/axelarjs-sdk/commit/8680d7407bf74d5df98f8c0519e5db1f904202e4
