### ISSUE TITLE
Have same contract addresses on all blockchains

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/axelarjs-sdk#286]
It would've been ideal for your contracts to have the same address across all blockchains.

Currently we can see that only some contracts have the same addresses as each other:
https://docs.axelar.dev/dev/reference/mainnet-contract-addresses
https://docs.axelar.dev/dev/reference/testnet-contract-addresses

What is the reason for the different addresses?
e.g. did you accidentally increase the nonce in the account that you used to deploy the particular contract?

I'd suggest to use a different method to deploy contracts to the same address across multiple blockchains that don't depend on your account or your nonce. e.g. by using replayable deployment transactions with manual signature.

**Comment by SKYBITDev3** [comment]
I've had a look at the Gateway Proxy contract creation transactions and found that both the "from" address and nonces vary, which is the cause of the different contract deployment addresses:

From|nonce|Gateway Proxy deployment address|Link to transaction
--|--|--|--
0xa57adce1d2fe72949e4308867d894cd7e7de0ef2|1|0x4f4495243837681061c4743b74b3eedf548d56a5|[Ethereum](https://etherscan.io/tx/0x40267874d285e467b86bfa2be66ae4a9a1338aed1309d6ca34f9c2a0a1531e62), [Moonbeam](https://moonscan.io/tx/0x3c2e6104051eac70b509f5fcf9639651520639b1d74983bbe8a7656ec1a2d36e)
0xa57adce1d2fe72949e4308867d894cd7e7de0ef2|2|0x304acf330bbe08d1e512eefaa92f6a57871fd895|[Fantom](https://ftmscan.com/tx/0x3789e4abf56d168a516f757b02e133e723df490d19b3ae98c7ebc4625e451e2c), [BNB Beacon Chain](https://bscscan.com/tx/0x229f61f4b37fe3cf02568e59461357744a2bcc5bbb2e1c12aedf3fe34f85121e)
0xa57adce1d2fe72949e4308867d894cd7e7de0ef2|3|0x6f015f16de9fc8791b234ef68d486d2bf203fba8|[Polygon](https://polygonscan.com/tx/0xce41d9bfea2956820e2d81555a21d6e0ec8bd02e7bed5bbf0bf7084d66f7b8bc)
0xa57adce1d2fe72949e4308867d894cd7e7de0ef2|8|0x5029c0eff6c34351a0cec334542cdb22c7928f78|[Avalanche C-Chain](https://snowtrace.io/tx/0xec1ade636737d71788557ccdf66b894a3f72e48a52bad5b66fdb59fcbe9f97d1)
0xb8cd93c83a974649d76b1c19f311f639e62272bc|3|0xe432150cce91c13a887f7d836923d5597add8e31|[Arbitrum](https://arbiscan.io/tx/0xf1eadc17f8a7ceafe7af7a420b4b1438f1a9eb56eb22c03cf9090827a28ac980), [Optimism](https://optimistic.etherscan.io/tx/0xe8b119394399b354e2632b3fa25094101ada5d9fac58174aaaa9fbd4c8804180), [Base](https://basescan.org/tx/0xeaa36b4efd8da3c08815d85bee9353eb492dde881d168c683c4318d511f0a9dc), [Linea](https://lineascan.build/tx/0x05e13e0483e4684d33d13723ed33a8eebe9afc61fafca81069ecf482b71126aa), [Celo](https://celoscan.io/tx/0x9e0d555beafac7eb89d96d1f8d841cfdbbc8a70114d33b673b8cd791496f692f) 

For the Gas service contract I see you managed to maintain the same nonce on all blockchains.

Wouldn't it be better to use a CREATE2 or CREATE3 factory to make it easier to get the same address on all blockchains, as the nonce wouldn't affect the calculated address? Even better is to use a replayable deployment transaction as then it wouldn't even matter which account deploys it, i.e. anyone can broadcast the transaction and the contract will appear at the same address as on other blockchains.

**Comment by re1ro** [comment]
The gateways were deployed before constant cross-chain address was a widespread thing. We are not going to redeploy them at this point because that would break apps already integrated with existing gateways. For all new services we are using our Create3Deployer factory.
