### ISSUE TITLE
Error Encountered while Estimating Crosschain Gas Fee for Arbitrum-Sepolia to Sepolia Chain

### ISSUE THREAD

**Issue by MisterDefender** [axelarnetwork/axelarjs-sdk#306]
**Description:**
When attempting to estimate cross-chain gas fees using AxelarJS-SDK for the Arbitrum-Sepolia to Sepolia chain transaction, an error is encountered:
`Error: Invalid chain identifier for arbitrum-sepolia. Did you mean arbitrum?`
However, it's noted that GMP Support for the arbitrum-sepolia chain is already live.

**Expected Behavior**:
The estimation should proceed without errors, recognizing the arbitrum-sepolia chain identifier.

**Actual Behavior**:
Encountered an error indicating an invalid chain identifier.

**Additional Information**:

AxelarJS-SDK version: `^0.14.1`

//estimateGas.js
```javascript
const {
  AxelarQueryAPI,
  Environment,
  EvmChain,
  GasToken,
  CHAINS,
} = require("@axelar-network/axelarjs-sdk");
const { ethers } = require("hardhat");

async function main() {
  const axelarSDK = new AxelarQueryAPI({
    environment: Environment.TESTNET,
  });

  const estimateGasUsed = 400000;
  const gasMultiplier = 1.1; // 10% Buffer for gas consumption

  const gasFee = await axelarSDK.estimateGasFee(
    CHAINS.TESTNET.ARBITRUM_SEPOLIA,
    CHAINS.TESTNET.SEPOLIA,
    GasToken.ARBITRUM_SEPOLIA,
    estimateGasUsed,
    gasMultiplier
  );

  console.log("Gas Required in ETHs:  ", ethers.formatEther(gasFee));

}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});


```

**Comment by aAnurag7** [comment]
i also faced this issue, pls look into it!!!

**Comment by sudhakarbaghel** [comment]
I am also facing same error!!

**Comment by truptiQL** [comment]
Same behaviour shown in my case as well

**Comment by MisterDefender** [comment]
They have updated the AxelarJS-SDK package with arbitrum sepolia support.
