### ISSUE TITLE
Autofill TokenName & Symbol during ITS token deployment 

### ISSUE THREAD

**Issue by blockchainguyy** [axelarnetwork/axelarjs-sdk#326]
Whenever a new token is deployed through [ITS Portal](https://interchain.axelar.dev/), after the token deployment auto fill details for TokenName and TokenSymbol in the attached google [form](https://docs.google.com/forms/d/1EoA2eYA5OK_BagoB4lgqiS67hIiDpZ7ssov1UUksD_Y)

**Comment by npty** [comment]
Ported the issue to [here](https://github.com/axelarnetwork/axelarjs/issues/360)
