### ISSUE TITLE
incorporate query for minimum transfer amount and fees

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelarjs-sdk#59]
the new testnet upgrade on march 9 will include a new query for fees that should be included here.

**Comment by milapsheth** [comment]
Query for fees on a transfer is: `axelard q nexus transfer-fee`
And to get fee info for an asset on a chain is: `axelard q nexus fee` (If fee info is not registered, it returns an error, and in this instance the network treats that as 0 fee for that asset).

**Comment by canhtrinh** [comment]
already implemented
