### ISSUE TITLE
Missing a function to check if tx has already been executed on the destination chain.

### ISSUE THREAD

**Issue by npty** [axelarnetwork/axelarjs-sdk#85]
At the moment, the SDK doesn't provide a way to check if the `callContract` or `callContractWithToken` tx is already executed or not.

**Comment by npty** [comment]
gateway contract just added this. so we can now implement it.
https://github.com/axelarnetwork/axelar-cgp-solidity/blob/main/src/interfaces/IAxelarGateway.sol#L101-L117

**Comment by canhtrinh** [comment]
@npty this is already done, right?

**Comment by npty** [comment]
Yes, i will close it.
